version: "3"
services:
  axmouth.disco-music-bot:
    working_dir: /var/lib/axmouth
    restart: unless-stopped
    tty: true
    image: ghcr.io/axmouth/disco-music-bot:latest
    container_name: axmouth.disco-music-bot
    env_file:
      - ./.env
    environment:
      - DATABASE_URL
      - DISCORD_TOKEN
      - REDIS_URL
      - YT_API_KEY
      - LAVALINK_HOST
      - LAVALINK_PORT
      - LAVALINK_PASSWORD=youshallnotpass
    networks:
      - axmouth.disco-music-bot-network
  # save prefixes, cache yt searches, play queue, playing state
  axmouth.disco-music-bot-redis:
    container_name: axmouth.disco-music-bot-redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 30 1 --loglevel warning
    links:
      - axmouth.disco-music-bot-lavalink:lavalink
    volumes:
        - ./disco-music-bo-redis-volume:/data
    networks:
      - axmouth.disco-music-bot-network
  axmouth.disco-music-bot-lavalink:
    container_name: axmouth.disco-music-bot-lavalink
    image: fredboat/lavalink:3.6.2
    environment:
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    networks:
      - axmouth.disco-music-bot-network

networks:
  axmouth.disco-music-bot-network:
    driver: bridge
